# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TsC2DIs_tnZqJhNEEL8d4IxrCRWxCzG
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

data = pd.read_csv('/content/IMDB Dataset.csv', on_bad_lines='skip', engine='python', encoding='latin1')

data.head(5)

data.replace({'sentiment': {'positive': 1, 'negative': 0}}, inplace=True)

data.head(5)

data.drop_duplicates(inplace = True)

data['review'] = data['review'].str.lower()

import re
def remove_html(text):
  pattern = r'[^a-ZA-Z0-9\S]'
  text = re.sub(pattern,'',text)
  return text

  data['review'] = data['review'].apply(remove_html)

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

data['review'] = data['review'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

data['review'] = data['review'].str.replace('http\S+','',case=False)

train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(train_data['review'])
x_train = pad_sequences(tokenizer.texts_to_sequences(train_data['review']), maxlen = 200)
x_test =  pad_sequences(tokenizer.texts_to_sequences(test_data['review']),maxlen = 200)

y_train = train_data['sentiment']
y_test = test_data['sentiment']

model = Sequential()

model.add(Embedding(input_dim = 5000, output_dim=128, input_shape=(200,)))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

model_sumary = model.summary()
print(model_sumary)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(x_train,y_train, epochs=10,batch_size=64, validation_split=0.2)

plt.figure()
plt.plot(history.history['accuracy'], label='train')
plt.plot(history.history['val_accuracy'], label='test')
plt.title("Accuracy")
plt.xlabel("acc")
plt.ylabel("epochs")
plt.legend()
plt.show()

loss, accuracy = model.evaluate(x_test, y_test)
print('loss',loss, "accuracy", accuracy)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

a = data['review']
b = data['sentiment']

x_train,x_test,y_train,y_test = train_test_split(a,b,test_size=0.2,random_state=42)

tfidf = TfidfVectorizer(max_features=5000,  stop_words='english')
x_train_tfidf = tfidf.fit_transform(x_train)
x_test_tfidf = tfidf.transform(x_test)

Log_reg = LogisticRegression(max_iter = 5000)
Log_reg.fit(x_train_tfidf,y_train)

y_pred = Log_reg.predict(x_test_tfidf)

accuracy = accuracy_score(y_test,y_pred)

print(accuracy)

import pickle

pickle.dump(tokenizer, open('tokenizer.pkl', 'wb'))
pickle.dump(model, open('model.pkl', 'wb'))

